// Generated by https://quicktype.io

export interface TopLevel {
    current_page: number;
    data: Factura[];
    first_page_url: string;
    from: number;
    last_page: number;
    last_page_url: string;
    links: Link[];
    next_page_url: null;
    path: string;
    per_page: number;
    prev_page_url: null;
    to: number;
    total: number;
}

export interface Factura {
    id?: number;
    concepto?: string;
    secuencia_factura_interna?: string;
    secuencia_factura_externa?: null;
    total?: string;
    sub_total?: string;
    impuesto_total?: string;
    hotel_id?: number;
    cliente_id?: number;
    porcentaje_descuento?: number;
    secuencia_interna?: number;
    secuencia_externa?: null;
    cufe?: null;
    estado?: number;
    created_at?: string;
    updated_at?: string;
    cliente?: Cliente;
    hotel?: Hotel;
}

export interface Cliente {
    id: number;
    nombres: string;
    apellidos: string;
}

export interface Hotel {
    id: number;
    nombre: string;
}

export interface Link {
    url: null | string;
    label: string;
    active: boolean;
}
